inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'db/migrate/**'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'db/seeds/*'
    - 'doc/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'spec/fixtures/**/*'
    - 'spec/support/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'notes/**/*'
    - 'node_modules/**/*'
    - 'Rakefile'

  TargetRubyVersion: 3.0

Rails:
  Enabled: true


Layout/LineLength:
   Max: 140

# Disable rules

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

# Enable rules

Lint/MissingSuper:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
